[package]
name = "prime_check_lookup_table"
version = "0.1.0"
authors = ["rustlearner"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
