[package]
name = "aes-ctr"
version = "0.1.0"
authors = ["Rust Student"]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'
debug = true

[dependencies]
structopt = "0"
hex = "0"
numrs = "0"